name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build and export toolkit
        run: cd toolkit && yarn build

      - name: Build and export the site
        run: cd ../documentation && yarn build

      - name: Deploy preview
        uses: amondnet/vercel-action@v20
        with:
          args: deploy --prod false --confirm --scope ${{ secrets.VERCEL_TEAM }} --token ${{ secrets.VERCEL_TOKEN }}